version: '3'
services:
    postgresql:
        container_name: directus_database
        image: postgis/postgis:13-master
        volumes:
            - directus_database:/var/lib/postgresql/data
        networks:
            - directus
        environment:
            POSTGRES_USER: 'directus'
            POSTGRES_PASSWORD: 'directus'
            POSTGRES_DB: 'directus'

    redis:
        container_name: directus_cache
        image: redis:6
        networks:
            - directus

    directus:
        container_name: directus
        image: directus/directus:latest
        ports:
            - 8088:8088
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        networks:
            - directus
        depends_on:
            - redis
            - postgresql
        environment:
            KEY: '255d441b-5ea1-9563-9aa3-922530ec40b2'
            SECRET: '6116687b-cda1-28c2-b5b5-c8022c45e264'

            DB_CLIENT: 'pg'
            DB_HOST: 'directus_database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'

            CACHE_ENABLED: 'true'
            CACHE_STORE: 'redis'
            CACHE_REDIS: 'redis://directus_cache:6379'

            ADMIN_EMAIL: 'rafa@rab-devs.com'
            ADMIN_PASSWORD: 'tfgdaw'

            REFRESH_TOKEN_COOKIE_NAME: 'auth_refresh_token'
            REFRESH_TOKEN_COOKIE_SAME_SITE: 'none'
            REFRESH_TOKEN_COOKIE_SECURE: 'true'

            CORS_ENABLED: 'true'
            CORS_ORIGIN: 'true'

            # PRODUCTION
            HOST: '0.0.0.0'
            PORT: 8088
            PUBLIC_URL: '/'
networks:
    directus:

volumes:
    directus_database:
